# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (ninth hour of each day)
  schedule: [{cron: "0 1 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@main
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ChangQingAAS
          template: classic
          base: header
          config_timezone: Asia/Shanghai
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200 
          plugin_habits_charts: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year     
          plugin_languages_recent_days: 10
          plugin_languages_recent_load: 300 
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 10
          plugin_wakatime_sections: time, languages, languages-graphs 
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: ChangQingAAS
