name: Waka Readme

on:
  schedule:
    - cron: '0 20 * * *'
  issue_comment:
    types: [created, ]
  push: 
    branches:
      - main

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: ChangQingAAS/ChangQingAAS@main
        with:
          WAKATIME_API_KEY: ${{a1d17779-2a79-4256-be21-b17c5f155b6c}}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: False
          SHOW_PROFILE_VIEWS : False
          SHOW_COMMIT : False
          SHOW_DAYS_OF_WEEK : False
          SHOW_LANGUAGE : True
          SHOW_OS : True
          SHOW_PROJECTS : False
          SHOW_TIMEZONE : False
          SHOW_EDITORS : True
          SHOW_LANGUAGE_PER_REPO : False
          SHOW_SHORT_INFO : False
          SHOW_LOC_CHART : False
